### ISSUE TITLE
Set main branch

### ISSUE THREAD

**Issue by JKatzwinkel** [cplutte/bts#7]
Hauptbranch ist bei Dir `master`. In den project settings unter `Branches` > `Default branch` koennte man das in `working_master` aendern, weil das ja auch der ist in den wir mergen. Dann musz man das nicht bei jedem pull request extra auswaehlen und auszerdem sieht man dann auch dasz was passiert wenn man die github-seite vom BTS oeffnet.

**Comment by cplutte** [comment]
main branch set to `<working_master>`
